import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service - SealTheDeal',
  description: 'Terms of Service for SealTheDeal contract management platform',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-900">
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-slate-800 rounded-xl border border-slate-700 p-8">
          <div className="mb-8">
            <Link href="/" className="text-blue-400 hover:text-blue-300 mb-4 inline-block">
              ← Back to Home
            </Link>
            <h1 className="text-3xl font-bold text-white mb-4">Terms of Service</h1>
            <p className="text-slate-400">Last updated: {new Date().toLocaleDateString()}</p>
          </div>

          <div className="prose prose-invert max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
              <p className="text-slate-300 mb-4">
                By accessing and using SealTheDeal ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
              <p className="text-slate-300 mb-4">
                SealTheDeal is a contract management platform that provides AI-powered contract generation, template management, and document organization tools. The service is designed to assist users in creating, managing, and organizing legal contracts and related documents.
              </p>
              <div className="bg-yellow-500/20 border border-yellow-500/30 rounded-lg p-4 mb-4">
                <p className="text-yellow-400 font-medium">
                  <strong>Important Legal Notice:</strong> SealTheDeal provides contract templates and AI-generated content for informational purposes only. This does not constitute legal advice, and users should consult with qualified legal professionals for specific legal matters.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">3. User Accounts and Registration</h2>
              <p className="text-slate-300 mb-4">
                To use certain features of the Service, you must register for an account. You agree to:
              </p>
              <ul className="list-disc list-inside text-slate-300 mb-4 space-y-2">
                <li>Provide accurate, current, and complete information during registration</li>
                <li>Maintain and update your account information to keep it accurate and current</li>
                <li>Maintain the security of your password and account</li>
                <li>Accept responsibility for all activities under your account</li>
                <li>Notify us immediately of any unauthorized use of your account</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">4. Acceptable Use Policy</h2>
              <p className="text-slate-300 mb-4">You agree not to use the Service to:</p>
              <ul className="list-disc list-inside text-slate-300 mb-4 space-y-2">
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe upon the rights of others</li>
                <li>Transmit or store malicious code, viruses, or harmful software</li>
                <li>Attempt to gain unauthorized access to the Service or related systems</li>
                <li>Use the Service for any illegal or unauthorized purpose</li>
                <li>Interfere with or disrupt the Service or servers</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">5. Content and Intellectual Property</h2>
              <h3 className="text-xl font-medium text-white mb-3">5.1 User Content</h3>
              <p className="text-slate-300 mb-4">
                You retain ownership of all content you create, upload, or store using the Service. By using the Service, you grant us a limited license to use, store, and process your content solely for the purpose of providing the Service to you.
              </p>
              
              <h3 className="text-xl font-medium text-white mb-3">5.2 AI-Generated Content</h3>
              <p className="text-slate-300 mb-4">
                Content generated by our AI systems is provided for informational purposes only. While we strive for accuracy, AI-generated content may contain errors and should not be considered legal advice. You are responsible for reviewing and validating all AI-generated content before use.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">6. Privacy and Data Protection</h2>
              <p className="text-slate-300 mb-4">
                Your privacy is important to us. Please review our Privacy Policy, which also governs your use of the Service, to understand our practices regarding the collection and use of your information.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">7. Payment Terms</h2>
              <p className="text-slate-300 mb-4">
                If you subscribe to a paid plan, you agree to pay all fees associated with your subscription. Fees are charged in advance on a monthly or annual basis, as applicable. All fees are non-refundable unless otherwise stated.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">8. Disclaimers and Limitations</h2>
              <div className="bg-red-500/20 border border-red-500/30 rounded-lg p-4 mb-4">
                <h3 className="text-lg font-medium text-red-400 mb-2">8.1 Legal Advice Disclaimer</h3>
                <p className="text-red-300">
                  THE SERVICE PROVIDES CONTRACT TEMPLATES AND AI-GENERATED CONTENT FOR INFORMATIONAL PURPOSES ONLY. THIS IS NOT LEGAL ADVICE. YOU SHOULD CONSULT WITH QUALIFIED LEGAL PROFESSIONALS FOR SPECIFIC LEGAL MATTERS.
                </p>
              </div>
              
              <h3 className="text-xl font-medium text-white mb-3">8.2 Service Availability</h3>
              <p className="text-slate-300 mb-4">
                The Service is provided "as is" and "as available" without warranties of any kind. We do not guarantee that the Service will be uninterrupted, secure, or error-free.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">9. Limitation of Liability</h2>
              <p className="text-slate-300 mb-4">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, SEALTHEDEAL SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">10. Termination</h2>
              <p className="text-slate-300 mb-4">
                We may terminate or suspend your account and access to the Service immediately, without prior notice, for any reason, including breach of these Terms of Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">11. Changes to Terms</h2>
              <p className="text-slate-300 mb-4">
                We reserve the right to modify these Terms of Service at any time. We will notify users of any material changes via email or through the Service. Continued use of the Service after such modifications constitutes acceptance of the updated terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">12. Governing Law</h2>
              <p className="text-slate-300 mb-4">
                These Terms of Service shall be governed by and construed in accordance with the laws of the United States, without regard to conflict of law principles.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-white mb-4">13. Contact Information</h2>
              <p className="text-slate-300 mb-4">
                If you have any questions about these Terms of Service, please contact us at:
              </p>
              <div className="bg-slate-700 rounded-lg p-4">
                <p className="text-slate-300">
                  Email: legal@sealthedeal.com<br />
                  Address: [Your Business Address]<br />
                  Phone: [Your Phone Number]
                </p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
